#!/bin/bash

setxkbmap us,il -option none
setxkbmap us,il -option grp:alt_caps_toggle
xmodmap -e "remove mod5 = ISO_Level3_Shift"
xmodmap -e "add mod1 = ISO_Level3_Shift"
xmodmap -e "keycode  62 = Shift_R Shift_R Shift_R  Shift_R "
